package com.syncadapters.czar.exchange.enums;

public enum UserInterface {

    HARDWARE_INVENTORY_ACTIVITY,
    HOME_ACTIVITY,
    HOME_USER_SOFTWARE_PROFILE_ACTIVITY,
    MESSAGE_ACTIVITY,
    SOFTWARE_PROFILE_DIALOG,
    CONVERSATIONS_FRAGMENT,
    INVENTORY_IN_FRAGMENT,

}
